### ISSUE TITLE
自定义关卡-冒险者和金币

### ISSUE THREAD

**Issue by poorerdai** [liyupi/sql-mother#27]
看答案中group_by adventurer_id,adventurer_name。但是adventurer_id已经是用户的唯一标识了，所以group_by adventurer_id应该就够了，没必要再加上adventurer_name了吧？

**Comment by liyupi** [comment]
如果你要查询 adventurer_id,adventurer_name 两个字段，那么 group by 也要包含这两个字段

**Comment by poorerdai** [comment]
如果是MySQL 8 sql_mode 默认开启了ONLY_FULL_GROUP_BY，查询的字段group by 需要包含，但是如果没有开启ONLY_FULL_GROUP_BY，只需要group by adventurer_id就可以了。
