### ISSUE TITLE
冒险者和金币答案

### ISSUE THREAD

**Issue by GGXXLL** [liyupi/sql-mother#3]
`SELECT adventurer_id, adventurer_name, SUM(reward_coins) AS total_reward_coins FROM rewards GROUP BY adventurer_id, adventurer_name ORDER BY total_reward_coins DESC LIMIT 3;`  

只 `group by adventurer_id` 也对🐔

**Comment by liyupi** [comment]
被你发现了 🐶 感兴趣的话可以优化下题目数据和答案哈哈
