### ISSUE TITLE
sql执行错误

### ISSUE THREAD

**Issue by caiji0618** [liyupi/sql-mother#51]
Cannot read properties of undefined (reading 'exec')

**Comment by zhf521** [comment]
我也遇到了这个问题，你可以尝试将SqlExecutor.ts文件中的第22行里面的cdn地址换成最新的版本,即：https://cdn.bootcdn.net/ajax/libs/sql.js/1.8.0/sql-wasm.wasm

**Comment by liyupi** [comment]
已修复
