### ISSUE TITLE
这家伙有授权吗

### ISSUE THREAD

**Issue by solidarity-forever** [liyupi/sql-mother#58]
https://www.xue-sql.online/
https://v2ex.com/t/1011018

**Comment by liyupi** [comment]
感谢小伙伴反馈，没有任何授权，纯纯盗版，勇气可嘉 👍🏻 
希望大家帮我证明下 🙏🏻

**Comment by valiner** [comment]
前排看戏

**Comment by tjsky** [comment]
他在各种平台里说和你沟通了，要求各种人删帖，他有对你道歉吗？

**Comment by JokerQyou** [comment]
他v2ex都删号了 :joy:

**Comment by tjsky** [comment]
> 他v2ex都删号了 😂

他目前在到处联系暗示删帖：“不要蹭流量了”

**Comment by liyupi** [comment]
我来说下这个事吧，告一段落。本来不想处理的，但看到该 UP 删了盗版帖子后继续挂着我做的网站并且没有任何对原作者（本人）的提及和授权，所以我联系了该 UP（没想到他正好是我的微信好友 😂），想问下他的想法和这么做的理由。

起初的交流不是很愉快，作者坚持认为开源项目就可以拿来随便用，改个作者名称就是自己的网站了？直到我表示不希望这件事情继续闹大，造成不必要的影响，该 UP 最终同意下架网站。

至于该 UP 什么删帖、或者换个人继续抄之类的，我管不着、也不想管，反正别抄我的就好了。如果需要转载内容，请跟我联系并授权，谢谢大家对正版的支持 💪🏻

**Comment by isPoto** [comment]
他在持续抹黑你，转发文章暗示你抄袭，也不是什么好东西

https://weibo.com/6155940089/NDBSxkuUQ

![image](https://github.com/liyupi/sql-mother/assets/59009389/f56eb1ee-d7e8-4061-a164-0feb99e28eb6)

**Comment by zhugezifang** [comment]
我是本人，目前项目已经下线，还是老有人估计搞事情，原文链接看这个 https://web.okjike.com/repost/65d1727d9185c305d1469abd

**Comment by tjsky** [comment]
> 我是本人，目前项目已经下线，还是老有人估计搞事情(真是闲着没事干，有这时间多写几行代码、多刷几道算法题不好吗)，原文链接看这个 https://web.okjike.com/repost/65d1727d9185c305d1469abd

还好v2ex不能自己删帖，你的发帖时咋说的“原创”？

**Comment by tjsky** [comment]
> 我是本人，目前项目已经下线，还是老有人估计搞事情(真是闲着没事干，有这时间多写几行代码、多刷几道算法题不好吗)，原文链接看这个 https://web.okjike.com/repost/65d1727d9185c305d1469abd

![Screenshot_20240312_181433_org.mozilla.firefox.jpg](https://github.com/liyupi/sql-mother/assets/7272911/473f9ea9-5c9a-46af-9aca-079b99612730)
原来阿里大数据工程师眼里的“独立开发”是这个意思啊。这是你的个人看法还是阿里统一的看法？
