### ISSUE TITLE
第17题，题目和答案对不上

### ISSUE THREAD

**Issue by RoadsideParty** [liyupi/sql-mother#6]
![2023-08-04_20-57-20](https://github.com/liyupi/sql-mother/assets/54093484/7759fde8-abdb-4ae6-9fed-fd55ea0ef534)
题目只要求查平均成绩，答案还查了对应id

**Comment by xuanyuTao** [comment]
我觉得没有问题，‘’每个班级的平均成绩“，没有class_id，只有avg_score的话，怎么知道是对应哪个班级的平均成绩

**Comment by liyupi** [comment]
确实不够清楚，已修改
